platform :ios, '16.0'

target 'GemNav' do
  use_frameworks!
  
  # Google Maps (required)
  pod 'GoogleMaps', '~> 8.0'
  
  # HERE SDK (binary XCFramework placeholder)
  # NOTE: Do NOT attempt to download. Only include this line.
  pod 'HEREMapsSDK', :path => '../here-sdk'
  
  # Firebase Crashlytics + Analytics
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  
  # Swift Protobuf (Google base types)
  pod 'SwiftProtobuf', '~> 1.24'
end
